version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: food-del-backend
    env_file: ./backend/.env
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - food-del-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: food-del-frontend
    ports:
      - "3000:80"
    networks:
      - food-del-network

  mongo:
    image: mongo:7
    container_name: food-del-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - food-del-network

networks:
  food-del-network:
    external: true

volumes:
  mongo-data: